version: '3.3'
services:
  bot:
    build:
      context: ./
    depends_on:
      - db
    restart: always
    environment:
      BotTokenAgentBlack: ${DISCORD_BOT_TOKEN}
      DBHost: db
      DBName: agentBlack
      DBUsername: ${DB_USERNAME}
      DBPassword: ${DB_PASSWORD}

  db:
    image: mariadb:latest
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: agentBlack
      MYSQL_USER: agentBlack
      MYSQL_PASSWORD: ${DB_PASSWORD}
volumes:
  db_data: